# Generated by Django 4.1.7 on 2023-06-03 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_allanswer_delete_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allans', to='app.question'),
        ),
    ]
